# BidiBrackets-13.0.0.txt
# fetched from: http://www.unicode.org/Public/UNIDATA/BidiMirroring.txt
# and converted to gdscript

const brackets = {
	"\u0028": ["\u0029", "o"], # LEFT PARENTHESIS
	"\u0029": ["\u0028", "c"], # RIGHT PARENTHESIS
	"\u005B": ["\u005D", "o"], # LEFT SQUARE BRACKET
	"\u005D": ["\u005B", "c"], # RIGHT SQUARE BRACKET
	"\u007B": ["\u007D", "o"], # LEFT CURLY BRACKET
	"\u007D": ["\u007B", "c"], # RIGHT CURLY BRACKET
	"\u0F3A": ["\u0F3B", "o"], # TIBETAN MARK GUG RTAGS GYON
	"\u0F3B": ["\u0F3A", "c"], # TIBETAN MARK GUG RTAGS GYAS
	"\u0F3C": ["\u0F3D", "o"], # TIBETAN MARK ANG KHANG GYON
	"\u0F3D": ["\u0F3C", "c"], # TIBETAN MARK ANG KHANG GYAS
	"\u169B": ["\u169C", "o"], # OGHAM FEATHER MARK
	"\u169C": ["\u169B", "c"], # OGHAM REVERSED FEATHER MARK
	"\u2045": ["\u2046", "o"], # LEFT SQUARE BRACKET WITH QUILL
	"\u2046": ["\u2045", "c"], # RIGHT SQUARE BRACKET WITH QUILL
	"\u207D": ["\u207E", "o"], # SUPERSCRIPT LEFT PARENTHESIS
	"\u207E": ["\u207D", "c"], # SUPERSCRIPT RIGHT PARENTHESIS
	"\u208D": ["\u208E", "o"], # SUBSCRIPT LEFT PARENTHESIS
	"\u208E": ["\u208D", "c"], # SUBSCRIPT RIGHT PARENTHESIS
	"\u2308": ["\u2309", "o"], # LEFT CEILING
	"\u2309": ["\u2308", "c"], # RIGHT CEILING
	"\u230A": ["\u230B", "o"], # LEFT FLOOR
	"\u230B": ["\u230A", "c"], # RIGHT FLOOR
	"\u2329": ["\u232A", "o"], # LEFT-POINTING ANGLE BRACKET
	"\u232A": ["\u2329", "c"], # RIGHT-POINTING ANGLE BRACKET
	"\u2768": ["\u2769", "o"], # MEDIUM LEFT PARENTHESIS ORNAMENT
	"\u2769": ["\u2768", "c"], # MEDIUM RIGHT PARENTHESIS ORNAMENT
	"\u276A": ["\u276B", "o"], # MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT
	"\u276B": ["\u276A", "c"], # MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT
	"\u276C": ["\u276D", "o"], # MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT
	"\u276D": ["\u276C", "c"], # MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
	"\u276E": ["\u276F", "o"], # HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT
	"\u276F": ["\u276E", "c"], # HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
	"\u2770": ["\u2771", "o"], # HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT
	"\u2771": ["\u2770", "c"], # HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT
	"\u2772": ["\u2773", "o"], # LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT
	"\u2773": ["\u2772", "c"], # LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT
	"\u2774": ["\u2775", "o"], # MEDIUM LEFT CURLY BRACKET ORNAMENT
	"\u2775": ["\u2774", "c"], # MEDIUM RIGHT CURLY BRACKET ORNAMENT
	"\u27C5": ["\u27C6", "o"], # LEFT S-SHAPED BAG DELIMITER
	"\u27C6": ["\u27C5", "c"], # RIGHT S-SHAPED BAG DELIMITER
	"\u27E6": ["\u27E7", "o"], # MATHEMATICAL LEFT WHITE SQUARE BRACKET
	"\u27E7": ["\u27E6", "c"], # MATHEMATICAL RIGHT WHITE SQUARE BRACKET
	"\u27E8": ["\u27E9", "o"], # MATHEMATICAL LEFT ANGLE BRACKET
	"\u27E9": ["\u27E8", "c"], # MATHEMATICAL RIGHT ANGLE BRACKET
	"\u27EA": ["\u27EB", "o"], # MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
	"\u27EB": ["\u27EA", "c"], # MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
	"\u27EC": ["\u27ED", "o"], # MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET
	"\u27ED": ["\u27EC", "c"], # MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
	"\u27EE": ["\u27EF", "o"], # MATHEMATICAL LEFT FLATTENED PARENTHESIS
	"\u27EF": ["\u27EE", "c"], # MATHEMATICAL RIGHT FLATTENED PARENTHESIS
	"\u2983": ["\u2984", "o"], # LEFT WHITE CURLY BRACKET
	"\u2984": ["\u2983", "c"], # RIGHT WHITE CURLY BRACKET
	"\u2985": ["\u2986", "o"], # LEFT WHITE PARENTHESIS
	"\u2986": ["\u2985", "c"], # RIGHT WHITE PARENTHESIS
	"\u2987": ["\u2988", "o"], # Z NOTATION LEFT IMAGE BRACKET
	"\u2988": ["\u2987", "c"], # Z NOTATION RIGHT IMAGE BRACKET
	"\u2989": ["\u298A", "o"], # Z NOTATION LEFT BINDING BRACKET
	"\u298A": ["\u2989", "c"], # Z NOTATION RIGHT BINDING BRACKET
	"\u298B": ["\u298C", "o"], # LEFT SQUARE BRACKET WITH UNDERBAR
	"\u298C": ["\u298B", "c"], # RIGHT SQUARE BRACKET WITH UNDERBAR
	"\u298D": ["\u2990", "o"], # LEFT SQUARE BRACKET WITH TICK IN TOP CORNER
	"\u298E": ["\u298F", "c"], # RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
	"\u298F": ["\u298E", "o"], # LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
	"\u2990": ["\u298D", "c"], # RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER
	"\u2991": ["\u2992", "o"], # LEFT ANGLE BRACKET WITH DOT
	"\u2992": ["\u2991", "c"], # RIGHT ANGLE BRACKET WITH DOT
	"\u2993": ["\u2994", "o"], # LEFT ARC LESS-THAN BRACKET
	"\u2994": ["\u2993", "c"], # RIGHT ARC GREATER-THAN BRACKET
	"\u2995": ["\u2996", "o"], # DOUBLE LEFT ARC GREATER-THAN BRACKET
	"\u2996": ["\u2995", "c"], # DOUBLE RIGHT ARC LESS-THAN BRACKET
	"\u2997": ["\u2998", "o"], # LEFT BLACK TORTOISE SHELL BRACKET
	"\u2998": ["\u2997", "c"], # RIGHT BLACK TORTOISE SHELL BRACKET
	"\u29D8": ["\u29D9", "o"], # LEFT WIGGLY FENCE
	"\u29D9": ["\u29D8", "c"], # RIGHT WIGGLY FENCE
	"\u29DA": ["\u29DB", "o"], # LEFT DOUBLE WIGGLY FENCE
	"\u29DB": ["\u29DA", "c"], # RIGHT DOUBLE WIGGLY FENCE
	"\u29FC": ["\u29FD", "o"], # LEFT-POINTING CURVED ANGLE BRACKET
	"\u29FD": ["\u29FC", "c"], # RIGHT-POINTING CURVED ANGLE BRACKET
	"\u2E22": ["\u2E23", "o"], # TOP LEFT HALF BRACKET
	"\u2E23": ["\u2E22", "c"], # TOP RIGHT HALF BRACKET
	"\u2E24": ["\u2E25", "o"], # BOTTOM LEFT HALF BRACKET
	"\u2E25": ["\u2E24", "c"], # BOTTOM RIGHT HALF BRACKET
	"\u2E26": ["\u2E27", "o"], # LEFT SIDEWAYS U BRACKET
	"\u2E27": ["\u2E26", "c"], # RIGHT SIDEWAYS U BRACKET
	"\u2E28": ["\u2E29", "o"], # LEFT DOUBLE PARENTHESIS
	"\u2E29": ["\u2E28", "c"], # RIGHT DOUBLE PARENTHESIS
	"\u3008": ["\u3009", "o"], # LEFT ANGLE BRACKET
	"\u3009": ["\u3008", "c"], # RIGHT ANGLE BRACKET
	"\u300A": ["\u300B", "o"], # LEFT DOUBLE ANGLE BRACKET
	"\u300B": ["\u300A", "c"], # RIGHT DOUBLE ANGLE BRACKET
	"\u300C": ["\u300D", "o"], # LEFT CORNER BRACKET
	"\u300D": ["\u300C", "c"], # RIGHT CORNER BRACKET
	"\u300E": ["\u300F", "o"], # LEFT WHITE CORNER BRACKET
	"\u300F": ["\u300E", "c"], # RIGHT WHITE CORNER BRACKET
	"\u3010": ["\u3011", "o"], # LEFT BLACK LENTICULAR BRACKET
	"\u3011": ["\u3010", "c"], # RIGHT BLACK LENTICULAR BRACKET
	"\u3014": ["\u3015", "o"], # LEFT TORTOISE SHELL BRACKET
	"\u3015": ["\u3014", "c"], # RIGHT TORTOISE SHELL BRACKET
	"\u3016": ["\u3017", "o"], # LEFT WHITE LENTICULAR BRACKET
	"\u3017": ["\u3016", "c"], # RIGHT WHITE LENTICULAR BRACKET
	"\u3018": ["\u3019", "o"], # LEFT WHITE TORTOISE SHELL BRACKET
	"\u3019": ["\u3018", "c"], # RIGHT WHITE TORTOISE SHELL BRACKET
	"\u301A": ["\u301B", "o"], # LEFT WHITE SQUARE BRACKET
	"\u301B": ["\u301A", "c"], # RIGHT WHITE SQUARE BRACKET
	"\uFE59": ["\uFE5A", "o"], # SMALL LEFT PARENTHESIS
	"\uFE5A": ["\uFE59", "c"], # SMALL RIGHT PARENTHESIS
	"\uFE5B": ["\uFE5C", "o"], # SMALL LEFT CURLY BRACKET
	"\uFE5C": ["\uFE5B", "c"], # SMALL RIGHT CURLY BRACKET
	"\uFE5D": ["\uFE5E", "o"], # SMALL LEFT TORTOISE SHELL BRACKET
	"\uFE5E": ["\uFE5D", "c"], # SMALL RIGHT TORTOISE SHELL BRACKET
	"\uFF08": ["\uFF09", "o"], # FULLWIDTH LEFT PARENTHESIS
	"\uFF09": ["\uFF08", "c"], # FULLWIDTH RIGHT PARENTHESIS
	"\uFF3B": ["\uFF3D", "o"], # FULLWIDTH LEFT SQUARE BRACKET
	"\uFF3D": ["\uFF3B", "c"], # FULLWIDTH RIGHT SQUARE BRACKET
	"\uFF5B": ["\uFF5D", "o"], # FULLWIDTH LEFT CURLY BRACKET
	"\uFF5D": ["\uFF5B", "c"], # FULLWIDTH RIGHT CURLY BRACKET
	"\uFF5F": ["\uFF60", "o"], # FULLWIDTH LEFT WHITE PARENTHESIS
	"\uFF60": ["\uFF5F", "c"], # FULLWIDTH RIGHT WHITE PARENTHESIS
	"\uFF62": ["\uFF63", "o"], # HALFWIDTH LEFT CORNER BRACKET
	"\uFF63": ["\uFF62", "c"]  # HALFWIDTH RIGHT CORNER BRACKET
}
